version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        # image: php:7.4-apache
        ports:
        - 80:80
        volumes:
        - ./src:/var/www/html/

    dbmy:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            # Root username = root
            MYSQL_ROOT_PASSWORD: punyahanif

    dbpg:
        image: postgres
        restart: always
        environment:
            # Root username = postgres
            POSTGRES_PASSWORD: punyahanif

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8888:80
        environment:
            - PMA_ARBITRARY=1

    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080